/**
 * Template registry (docs/05-architecture.md §9): metadata only — tiny and server-safe, used by
 * static pages, search, sitemap and OG images — plus lazy loaders, which only the render worker
 * calls, so template code never ships to the main thread.
 */

import type { AlphaSupport, AnyTemplate, CategoryId, FormatId, Structure } from '@/engine';

export type TemplateEntry = {
  id: string;
  name: string;
  tagline: string;
  category: CategoryId;
  /** The first format is the default. */
  formats: readonly FormatId[];
  duration: { default: number | 'auto'; min: number; max: number };
  structure: Structure;
  alpha: AlphaSupport;
  tags: readonly string[];
  useCases: readonly string[];
};

export const TEMPLATES: readonly TemplateEntry[] = [
  {
    id: 'rise',
    name: 'Rise',
    tagline: 'Masked line reveal',
    category: 'text-titles',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 5, min: 3, max: 12 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['title', 'chapter', 'editorial', 'headline'],
    useCases: ['Chapter titles', 'Keynote headlines', 'Documentary title cards', 'YouTube'],
  },
  {
    id: 'focus',
    name: 'Focus',
    tagline: 'Blur-to-sharp headline',
    category: 'text-titles',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 5, min: 3, max: 12 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['title', 'headline', 'announcement', 'blur', 'premium'],
    useCases: ['Announcements', 'Product teasers', 'Keynote statements', 'Premium intros'],
  },
  {
    id: 'decode',
    name: 'Decode',
    tagline: 'Character scramble',
    category: 'text-titles',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 4, min: 3, max: 10 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['title', 'tech', 'scramble', 'terminal', 'teaser'],
    useCases: ['Tech launches', 'Teasers', 'Gaming', 'Podcast intros'],
  },
  {
    id: 'stretch',
    name: 'Stretch',
    tagline: 'Variable-width poster type',
    category: 'text-titles',
    formats: ['9:16', '1:1', '4:5', '16:9'],
    duration: { default: 4, min: 3, max: 10 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['title', 'poster', 'variable font', 'kinetic', 'bold'],
    useCases: ['Music drops', 'Event posters', 'Social hooks', 'Campaign slogans'],
  },
  {
    id: 'echo',
    name: 'Echo',
    tagline: 'Stacked outline repeats',
    category: 'text-titles',
    formats: ['9:16', '4:5', '1:1', '16:9'],
    duration: { default: 5, min: 3, max: 10 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['title', 'kinetic', 'poster', 'outline', 'music'],
    useCases: ['Kinetic posters', 'Music and culture', 'Reels hooks', 'Event teasers'],
  },
  {
    id: 'line',
    name: 'Line',
    tagline: 'Minimal accent bar',
    category: 'lower-thirds',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 6, min: 3, max: 20 },
    structure: 'in-hold-out',
    alpha: 'default',
    tags: ['lower third', 'name', 'interview', 'minimal'],
    useCases: ['Interviews', 'Webinars', 'Corporate video', 'Talking heads'],
  },
  {
    id: 'broadcast',
    name: 'Broadcast',
    tagline: 'News block',
    category: 'lower-thirds',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 6, min: 3, max: 20 },
    structure: 'in-hold-out',
    alpha: 'default',
    tags: ['lower third', 'name', 'news', 'live', 'sports'],
    useCases: ['News-style content', 'Event coverage', 'Live streams', 'Sports'],
  },
  {
    id: 'capsule',
    name: 'Capsule',
    tagline: 'Creator pill',
    category: 'lower-thirds',
    formats: ['9:16', '16:9', '1:1', '4:5'],
    duration: { default: 6, min: 3, max: 20 },
    structure: 'in-hold-out',
    alpha: 'default',
    tags: ['lower third', 'name', 'creator', 'social', 'follow'],
    useCases: ['YouTubers', 'Podcasters', 'Streamers', 'Guest intros'],
  },
  {
    id: 'editorial',
    name: 'Editorial',
    tagline: 'Serif elegance',
    category: 'lower-thirds',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 7, min: 3, max: 20 },
    structure: 'in-hold-out',
    alpha: 'default',
    tags: ['lower third', 'name', 'serif', 'documentary', 'luxury'],
    useCases: ['Documentaries', 'Fashion', 'Luxury brands', 'Museum and culture'],
  },
  {
    id: 'signal',
    name: 'Signal',
    tagline: 'Tech HUD',
    category: 'lower-thirds',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 6, min: 3, max: 20 },
    structure: 'in-hold-out',
    alpha: 'default',
    tags: ['lower third', 'name', 'tech', 'hud', 'gaming'],
    useCases: ['Tech talks', 'Gaming and esports', 'Hackathons', 'Product demos', 'Conferences'],
  },
  {
    id: 'punch',
    name: 'Punch',
    tagline: 'Kinetic hook captions',
    category: 'social',
    formats: ['9:16', '1:1', '4:5', '16:9'],
    duration: { default: 'auto', min: 4, max: 15 },
    structure: 'sequence',
    alpha: 'optional',
    tags: ['hook', 'captions', 'kinetic type', 'reels', 'bold'],
    useCases: ['Reel hooks', 'TikTok openers', 'Quotes as video', 'Captions over footage'],
  },
  {
    id: 'listicle',
    name: 'Listicle',
    tagline: 'Numbered tips',
    category: 'social',
    formats: ['9:16', '1:1', '4:5', '16:9'],
    duration: { default: 'auto', min: 6, max: 24 },
    structure: 'sequence',
    alpha: 'none',
    tags: ['list', 'tips', 'top 3', 'how to', 'numbers'],
    useCases: ['Educational posts', 'Tips and tricks', 'Carousel to video', 'How-tos'],
  },
  {
    id: 'countdown',
    name: 'Countdown',
    tagline: 'Launch timer',
    category: 'social',
    formats: ['9:16', '1:1', '4:5', '16:9'],
    duration: { default: 'auto', min: 4, max: 20 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['countdown', 'timer', 'launch', 'drop', 'event'],
    useCases: ['Product drops', 'Launches', 'Events', "New Year's", 'Live-stream starts'],
  },
  {
    id: 'deal',
    name: 'Deal',
    tagline: 'Price drop',
    category: 'product-ads',
    formats: ['1:1', '4:5', '9:16', '16:9'],
    duration: { default: 6, min: 4, max: 12 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['price', 'discount', 'product', 'sale', 'ecommerce'],
    useCases: ['Discounts', 'E-commerce promos', 'Flash offers', 'Marketplace ads'],
  },
  {
    id: 'sale',
    name: 'Sale',
    tagline: 'Promo tape',
    category: 'product-ads',
    formats: ['1:1', '4:5', '9:16', '16:9'],
    duration: { default: 5, min: 4, max: 12 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['sale', 'discount', 'promo', 'marquee', 'code'],
    useCases: ['Seasonal sales', 'Black Friday', 'Promo codes', 'Store openings'],
  },
  {
    id: 'callouts',
    name: 'Callouts',
    tagline: 'Feature callouts',
    category: 'product-ads',
    formats: ['16:9', '1:1', '4:5', '9:16'],
    duration: { default: 7, min: 5, max: 15 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['product', 'features', 'specs', 'callouts', 'launch'],
    useCases: [
      'Product features',
      'Spec highlights',
      'Launch explainers',
      'Hardware and packaging',
    ],
  },
  {
    id: 'reveal',
    name: 'Reveal',
    tagline: 'Hero launch',
    category: 'product-ads',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 7, min: 5, max: 15 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['product', 'launch', 'reveal', 'premium', 'light'],
    useCases: ['Product launches', 'Coming soon', 'Premium announcements', 'Hardware reveals'],
  },
  {
    id: 'compare',
    name: 'Compare',
    tagline: 'Before / after',
    category: 'product-ads',
    formats: ['1:1', '4:5', '9:16', '16:9'],
    duration: { default: 6, min: 4, max: 12 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['before after', 'comparison', 'redesign', 'photo edit', 'slider'],
    useCases: ['Redesigns', 'Photo edits', 'Renovations', 'Skincare', 'App updates', 'Glow-ups'],
  },
  {
    id: 'columns',
    name: 'Columns',
    tagline: 'Parallax portfolio reel',
    category: 'showcase',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 8, min: 5, max: 20 },
    structure: 'loop',
    alpha: 'none',
    tags: ['portfolio', 'gallery', 'parallax', 'loop', 'reel'],
    useCases: ['Studio reels', 'Portfolio intros', 'Collection launches', 'Mood reels'],
  },
  {
    id: 'stack',
    name: 'Stack',
    tagline: 'Photo stack',
    category: 'showcase',
    formats: ['1:1', '4:5', '9:16', '16:9'],
    duration: { default: 7, min: 5, max: 15 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['photos', 'travel', 'memories', 'collage', 'recap'],
    useCases: ['Travel recaps', 'Events', 'Memories', 'Year in review'],
  },
  {
    id: 'quote',
    name: 'Quote',
    tagline: 'Big quote',
    category: 'brand-quotes',
    formats: ['1:1', '4:5', '9:16', '16:9'],
    duration: { default: 'auto', min: 5, max: 12 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['quote', 'testimonial', 'editorial', 'speaker'],
    useCases: ['Quotes', 'Speaker highlights', 'Podcast clips', 'Thought leadership'],
  },
  {
    id: 'review',
    name: 'Review',
    tagline: 'Testimonial with rating',
    category: 'brand-quotes',
    formats: ['1:1', '4:5', '9:16', '16:9'],
    duration: { default: 6, min: 4, max: 12 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['review', 'testimonial', 'rating', 'stars', 'social proof'],
    useCases: ['Reviews', 'App ratings', 'Customer love', 'Case-study teasers'],
  },
  {
    id: 'numbers',
    name: 'Numbers',
    tagline: 'By the numbers',
    category: 'brand-quotes',
    formats: ['16:9', '1:1', '4:5', '9:16'],
    duration: { default: 6, min: 4, max: 12 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['stats', 'numbers', 'results', 'data', 'counter'],
    useCases: ['Year in review', 'Investor updates', 'Impact reports', 'Milestones'],
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    tagline: 'Film title',
    category: 'openers',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 8, min: 6, max: 15 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['opener', 'film', 'title', 'trailer', 'letterbox'],
    useCases: ['Short films', 'Documentaries', 'Trailers', 'Wedding films', 'Brand stories'],
  },
  {
    id: 'episode',
    name: 'Episode',
    tagline: 'Series opener',
    category: 'openers',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 5, min: 4, max: 10 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['opener', 'podcast', 'series', 'episode', 'intro'],
    useCases: ['Podcasts', 'YouTube series', 'Webinars', 'Courses'],
  },
  {
    id: 'layers',
    name: 'Layers',
    tagline: 'Stacked panel wipe',
    category: 'transitions',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 1.2, min: 0.6, max: 2.4 },
    structure: 'transition',
    alpha: 'default',
    tags: ['transition', 'wipe', 'panels', 'overlay'],
    useCases: ['Vlogs', 'Promos', 'Social edits', 'Scene changes'],
  },
  {
    id: 'iris',
    name: 'Iris',
    tagline: 'Circle burst',
    category: 'transitions',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 1.2, min: 0.6, max: 2.4 },
    structure: 'transition',
    alpha: 'default',
    tags: ['transition', 'circle', 'iris', 'reveal', 'overlay'],
    useCases: ['Reveals', 'Playful edits', 'Kids & education', 'Portal moments'],
  },
  {
    id: 'blinds',
    name: 'Blinds',
    tagline: 'Strip slices',
    category: 'transitions',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 1, min: 0.6, max: 2 },
    structure: 'transition',
    alpha: 'default',
    tags: ['transition', 'strips', 'blinds', 'graphic', 'overlay'],
    useCases: ['Corporate', 'Fashion', 'Editorial', 'Architecture'],
  },
  {
    id: 'sheen',
    name: 'Sheen',
    tagline: 'Light sweep',
    category: 'logo-branding',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 4, min: 3, max: 8 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['logo', 'reveal', 'light', 'premium'],
    useCases: ['Corporate intros', 'Premium brands', 'End cards', 'Event sponsors'],
  },
  {
    id: 'bounce',
    name: 'Bounce',
    tagline: 'Playful drop',
    category: 'logo-branding',
    formats: ['16:9', '9:16', '1:1', '4:5'],
    duration: { default: 4, min: 3, max: 8 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['logo', 'bounce', 'playful', 'physics'],
    useCases: ["Kids' brands", 'Apps', 'Food & drink', 'Friendly startups'],
  },
  {
    id: 'click',
    name: 'Click',
    tagline: 'Cursor demo',
    category: 'ui-motion',
    formats: ['16:9', '1:1', '4:5', '9:16'],
    duration: { default: 6, min: 5, max: 12 },
    structure: 'in-hold-out',
    alpha: 'optional',
    tags: ['ui', 'cursor', 'product', 'demo', 'fintech'],
    useCases: ['SaaS feature demos', 'Onboarding clips', 'Fintech and payments', 'How it works'],
  },
  {
    id: 'dashboard',
    name: 'Dashboard',
    tagline: 'Analytics build',
    category: 'ui-motion',
    formats: ['16:9', '1:1', '4:5', '9:16'],
    duration: { default: 7, min: 5, max: 12 },
    structure: 'in-hold-out',
    alpha: 'none',
    tags: ['ui', 'dashboard', 'charts', 'data', 'saas'],
    useCases: ['SaaS launches', 'Investor updates', 'Analytics features', 'Monthly reports'],
  },
];

const LOADERS: Readonly<Record<string, () => Promise<{ default: AnyTemplate }>>> = {
  rise: () => import('./text-titles/rise'),
  focus: () => import('./text-titles/focus'),
  decode: () => import('./text-titles/decode'),
  stretch: () => import('./text-titles/stretch'),
  echo: () => import('./text-titles/echo'),
  line: () => import('./lower-thirds/line'),
  broadcast: () => import('./lower-thirds/broadcast'),
  capsule: () => import('./lower-thirds/capsule'),
  editorial: () => import('./lower-thirds/editorial'),
  signal: () => import('./lower-thirds/signal'),
  punch: () => import('./social/punch'),
  listicle: () => import('./social/listicle'),
  countdown: () => import('./social/countdown'),
  deal: () => import('./product-ads/deal'),
  sale: () => import('./product-ads/sale'),
  callouts: () => import('./product-ads/callouts'),
  reveal: () => import('./product-ads/reveal'),
  compare: () => import('./product-ads/compare'),
  columns: () => import('./showcase/columns'),
  stack: () => import('./showcase/stack'),
  quote: () => import('./brand-quotes/quote'),
  review: () => import('./brand-quotes/review'),
  numbers: () => import('./brand-quotes/numbers'),
  cinematic: () => import('./openers/cinematic'),
  episode: () => import('./openers/episode'),
  layers: () => import('./transitions/layers'),
  iris: () => import('./transitions/iris'),
  blinds: () => import('./transitions/blinds'),
  sheen: () => import('./logo-branding/sheen'),
  bounce: () => import('./logo-branding/bounce'),
  click: () => import('./ui-motion/click'),
  dashboard: () => import('./ui-motion/dashboard'),
};

export function templateEntry(id: string): TemplateEntry | undefined {
  return TEMPLATES.find((entry) => entry.id === id);
}

/** Loads a template's code (render worker only). */
export async function loadTemplate(id: string): Promise<AnyTemplate> {
  const loader = Object.hasOwn(LOADERS, id) ? LOADERS[id] : undefined;
  if (!loader) throw new Error(`Unknown template "${id}"`);
  return (await loader()).default;
}
