/**
 * Licenses (docs/02-experience.md §2): Ugoki's own copyright (all rights reserved — decision A5),
 * every font family it ships (SIL OFL 1.1, with the copyright notices and links to the full texts
 * in public/fonts/licenses/) and its open-source packages (the full texts are in
 * public/legal/third-party-notices.txt). The lists come from `licenses.json`, generated by
 * `pnpm run licenses` (scripts/licenses.mjs). German summary first, then the English version with
 * the lists — the license texts themselves are English.
 */

import { ugokiJp } from '@/app/fonts';
import { LegalPage, linkClass } from './legal-page';
import data from './licenses.json';
import { COPYRIGHT_YEAR, OPERATOR } from './operator';
import { Topic } from './prose';

const NOTICES = '/legal/third-party-notices.txt';

type Font = (typeof data.fonts)[number];

const copyright = `© ${COPYRIGHT_YEAR} ${OPERATOR.name}`;

export function Licenses() {
  return (
    <LegalPage
      path="/legal/licenses"
      de={{
        title: 'Lizenzen',
        lead: (
          <p>
            Ugoki baut auf Schriften und Open-Source-Software auf, die andere geschaffen haben. Hier
            sind sie, mit ihren Lizenzen.
          </p>
        ),
        children: (
          <>
            <Topic title="Ugoki">
              <p className="text-fg">{copyright}. Alle Rechte vorbehalten.</p>
            </Topic>
            <Topic title="Schriften">
              <p>
                Alle Schriften in Ugoki stehen unter der SIL Open Font License&nbsp;1.1. Ugoki
                liefert angepasste Fassungen aus (Teilmengen der Zeichen, festgelegte Achsen);
                Schriften mit einem reservierten Namen tragen deshalb einen eigenen: Mona Sans heißt
                hier „Ugoki Sans“, Mona Sans Mono „Ugoki Mono“ und Hubot Sans „Ugoki Tech“. Alle{' '}
                {data.fonts.length} Schriftfamilien mit Urheberrechtshinweisen und Lizenztexten
                stehen in der{' '}
                <a href="#fonts" className={linkClass}>
                  englischen Fassung
                </a>
                .
              </p>
            </Topic>
            <Topic title="Open-Source-Software">
              <p>
                Ugoki nutzt {data.packages.length} Open-Source-Pakete. Die Liste mit Version und
                Lizenz jedes Pakets steht in der{' '}
                <a href="#software" className={linkClass}>
                  englischen Fassung
                </a>
                , die vollständigen Lizenztexte in{' '}
                <a href={NOTICES} className={linkClass}>
                  third-party-notices.txt
                </a>
                .
              </p>
            </Topic>
          </>
        ),
      }}
      en={{
        title: 'Licenses',
        lead: (
          <p>
            Ugoki is built on typefaces and open-source software that others made. Here they are,
            with their licenses.
          </p>
        ),
        children: (
          <>
            <Topic level={3} title="Ugoki">
              <p className="text-fg">{copyright}. All rights reserved.</p>
            </Topic>
            <Topic level={3} id="fonts" title="Fonts">
              <p>
                Every typeface in Ugoki is licensed under the SIL Open Font License&nbsp;1.1. Ugoki
                ships modified versions — subset and instanced — so families with a Reserved Font
                Name appear under new names: Mona Sans as “Ugoki Sans”, Mona Sans Mono as “Ugoki
                Mono” and Hubot Sans as “Ugoki Tech”.
              </p>
              <ul className="mt-8 border-line border-b">
                {data.fonts.map((font) => (
                  <FontEntry key={font.family} font={font} />
                ))}
              </ul>
            </Topic>
            <Topic level={3} id="software" title="Open-source software">
              <p>
                Ugoki’s code builds on these {data.packages.length} packages — its dependencies and
                theirs. The full license texts are in{' '}
                <a href={NOTICES} className={linkClass}>
                  third-party-notices.txt
                </a>
                .
              </p>
              <ul className="mt-8 border-line border-b md:columns-2 md:gap-x-8">
                {data.packages.map((entry) => (
                  <li
                    key={`${entry.name}@${entry.version}`}
                    className="flex min-h-11 break-inside-avoid items-baseline justify-between gap-4 border-line border-t py-2.5 text-small"
                  >
                    <span className="min-w-0 [overflow-wrap:anywhere]">
                      <a href={entry.repository} rel="noreferrer" className={linkClass}>
                        {entry.name}
                      </a>{' '}
                      <span className="text-fg-3">{entry.version}</span>
                    </span>
                    <span className="shrink-0 text-fg-3">{entry.license}</span>
                  </li>
                ))}
              </ul>
            </Topic>
          </>
        ),
      }}
    />
  );
}

const USES: Record<string, string> = { interface: 'Interface', templates: 'Templates' };

/** One font family: its name as shipped, where it's used, its origin and its copyright. */
function FontEntry({ font }: { font: Font }) {
  return (
    <li className="border-line border-t py-5 text-small">
      <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
        <span className="font-[600] text-[17px] text-fg">{font.family}</span>
        <span className="text-fg-3">
          {font.use.map((use, index) => (
            <span key={use}>
              {index > 0 ? ' · ' : null}
              {use === 'signature' ? (
                <>
                  The{' '}
                  <span lang="ja" className={ugokiJp.className}>
                    動き
                  </span>{' '}
                  signature
                </>
              ) : (
                USES[use]
              )}
            </span>
          ))}
          {font.italic ? ' · Roman and italic' : null}
        </span>
      </div>
      <p className="mt-1.5 text-fg-2">{font.renamed ? `A modified ${font.credit}` : font.credit}</p>
      <p className="mt-1.5 text-fg-3 [overflow-wrap:anywhere]">{font.copyright}</p>
      <p className="mt-2">
        <a href={font.licenseFile} className={linkClass}>
          SIL Open Font License 1.1
        </a>
      </p>
    </li>
  );
}
